"""Initial tables

Revision ID: 3a92984c5ed2
Revises: 
Create Date: 2021-04-17 01:15:59.682913

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "3a92984c5ed2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "adapters",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("send_to", sa.String(), nullable=False),
        sa.Column("translation_query", sa.String(), nullable=False),
        sa.Column("last_access", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_adapters_id"), "adapters", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_adapters_id"), table_name="adapters")
    op.drop_table("adapters")
    # ### end Alembic commands ###
