"""change send_to to URLType

Revision ID: efa3813fc2fb
Revises: 3a92984c5ed2
Create Date: 2021-04-17 14:14:22.143857

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "efa3813fc2fb"
down_revision = "3a92984c5ed2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
